name: symtdd
channels:
  - conda-forge
dependencies:
  - quimb ~= 1.4
  - graphviz ~= 7.1.0
  - python-graphviz ~= 0.20.1
  - pip
  - pip:
    - qiskit[visualization] ~= 0.42
    - git+https://github.com/jcmgray/cotengra.git
    - -r requirements-dev.txt
