name: symtdd
channels:
  - conda-forge
dependencies:
  - qiskit[visualization] ~= 0.42
  - quimb ~= 1.4
  - graphviz ~= 7.1.0
  - python-graphviz ~= 0.20.1
  - pip:
    - -e git+https://github.com/jcmgray/cotengra.git
    - -r requrirements-dev.txt
