name: 'Setup Python + Poetry environment'
description: 'Setup Python + Poetry environment'

inputs:
  python-version:
    required: false
    description: 'Python version'
    default: '3.10'
outputs: {}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.python-version}}
    - name: Install dependencies
      run: pip install ".[dev]"
      shell: bash
